In [2]:
import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import warnings

In [3]:
# 매직명령어 사용
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

mpl.rc('font', family = 'malgun gothic') # 폰트 설정
mpl.rc('axes', unicode_minus = False) # 유니코드에서 음수 부호 설정

# 차트 스타일 설정
sns.set(font = "malgun gothic", rc = {"axes.unicode_minus":False}, style = "darkgrid")
plt.rc('figure', figsize = (10, 8))

warnings.filterwarnings('ignore')

In [4]:
oil = pd.read_csv('C:/k_digital/source/Machine Learning with Python/ML project/oil/data_info.csv')
oil

           Feature Name                       Description
0   COMPONENT_ARBITRARY  샘플 오일 관련 부품 (Component 4종, 비식별화)
1           ANONYMOUS_1             무명 Feautre 1. 수치형 데이터
2                  YEAR               오일 샘플 및 진단 해 (Year)
3   SAMPLE_TRANSFER_DAY    오일 샘플링 후 진단 기관으로 이동한 기간 (Days)
4           ANONYMOUS_2             무명 Feautre 2. 수치형 데이터
5                    AG              원소기호 AG - Silver 함유량
6                    AL           원소기호 AL - Aluminium 함유량
7                     B                원소기호 B - Boron 함유량
8                    BA             원소기호 BA -  Barium 함유량
9                    BE           원소기호 BE - Beryllium 함유량
10                   CA             원소기호 CA - Calcium 함유량
11                   CD             원소기호 CD - Cadmium 함유량
12                   CO              원소기호 CO - Cobolt 함유량
13                   CR            원소기호 CR - Chromium 함유량
14                   CU              원소기호 CU - Copper 함유량
15                 FH2O                Water 수치(By FT-IR)
16                 FNOX                  NOx 수치(By FT-IR)
17         FOPTIMETHGLY                              비식별화
18                FOXID            Oxidation 수치(By FT-IR)
19                 FSO4                  SO4 수치(By FT-IR)
20                 FTBN            염기성 첨가제물질 수치(By FT-IR)
21                   FE                원소기호 FE - Iron 함유량
22                 FUEL                            연료 함유량
23                  H2O                         Water 함유량
24                    K            원소기호 K - Potassium 함유량
25                   LI             원소기호 LI - Lithium 함유량
26                   MG           원소기호 MG - Magnesium 함유량
27                   MN           원소기호 MN - Manganese 함유량
28                   MO          원소기호 MO - Molybdenum 함유량
29                  NaN              원소기호 NA - Sodium 함유량
30                   NI              원소기호 NI - Nickel 함유량
31                    P           원소기호 P - Phosphorus 함유량
32                   PB                원소기호 PB - Lead 함유량
33              PQINDEX         Particle Quantifier Index
34                    S              원소기호 S - Sulphur 함유량
35                   SB            원소기호 SB - Antimony 함유량
36                   SI            원소기호 SI - Silicone 함유량
37                   SN                 원소기호 SN - Tin 함유량
38       SOOTPERCENTAGE                       Soot 함유량(%)
39                   TI            원소기호 TI - Titanium 함유량
40                 U100    Particle Count (100㎛ 이상 크기 입자)
41                  U75     Particle Count (75㎛ 이상 크기 입자)
42                  U50     Particle Count (50㎛ 이상 크기 입자)
43                  U25     Particle Count (25㎛ 이상 크기 입자)
44                  U20     Particle Count (20㎛ 이상 크기 입자)
45                  U14     Particle Count (14㎛ 이상 크기 입자)
46                   U6      Particle Count (6㎛ 이상 크기 입자)
47                   U4      Particle Count (4㎛ 이상 크기 입자)
48                    V             원소기호 V - Vanadium 함유량
49                 V100           Viscosity @ 100 degrees
50                  V40            Viscosity @ 40 degrees
51                   ZN                원소기호 ZN - Zinc 함유량
52              Y_LABEL         오일 정상 여부 (0 : 정상, 1 : 이상)

In [5]:
oil_train = pd.read_csv('C:/k_digital/source/Machine Learning with Python/ML project/oil/train.csv')
oil_train

,ID,COMPONENT_ARBITRARY,ANONYMOUS_1,YEAR,SAMPLE_TRANSFER_DAY,ANONYMOUS_2,AG,AL,B,BA,...,U25,U20,U14,U6,U4,V,V100,V40,ZN,Y_LABEL
0,TRAIN_00000,COMPONENT3,1486,2011,7,200,0,3,93,0,...,NaN,NaN,NaN,NaN,NaN,0,NaN,154.0,75,0
1,TRAIN_00001,COMPONENT2,1350,2021,51,375,0,2,19,0,...,2.0,4.0,6.0,216.0,1454.0,0,NaN,44.0,652,0
2,TRAIN_00002,COMPONENT2,2415,2015,2,200,0,110,1,1,...,0.0,3.0,39.0,11261.0,41081.0,0,NaN,72.6,412,1
3,TRAIN_00003,COMPONENT3,7389,2010,2,200,0,8,3,0,...,NaN,NaN,NaN,NaN,NaN,0,NaN,133.3,7,0
4,TRAIN_00004,COMPONENT3,3954,2015,4,200,0,1,157,0,...,NaN,NaN,NaN,NaN,NaN,0,NaN,133.1,128,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14090,TRAIN_14090,COMPONENT3,1616,2014,8,200,0,2,201,1,...,NaN,NaN,NaN,NaN,NaN,0,NaN,135.4,16,0
14091,TRAIN_14091,COMPONENT1,2784,2013,2,200,0,3,85,0,...,NaN,NaN,NaN,NaN,NaN,0,14.5,117.5,1408,0
14092,TRAIN_14092,COMPONENT3,1788,2008,9,550,0,6,0,1,...,NaN,NaN,NaN,NaN,NaN,0,NaN,54.0,1301,0
14093,TRAIN_14093,COMPONENT2,2498,2009,19,550,0,2,4,0,...,7.0,8.0,100.0,1625.0,18890.0,0,NaN,44.3,652,0
14094,TRAIN_14094,COMPONENT2,1902,2012,15,200,0,0,77,0,...,1163.0,2565.0,11296.0,181016.0,325823.0,0,NaN,47.0,612,0

In [7]:
oil_test = pd.read_csv('C:/k_digital/source/Machine Learning with Python/ML project/oil/test.csv')
oil_test

,ID,COMPONENT_ARBITRARY,ANONYMOUS_1,YEAR,ANONYMOUS_2,AG,CO,CR,CU,FE,H2O,MN,MO,NI,PQINDEX,TI,V,V40,ZN
0,TEST_0000,COMPONENT1,2192,2016,200,0,0,0,1,12,0.0,0,0,0,10,0,0,91.3,1091
1,TEST_0001,COMPONENT3,2794,2011,200,0,0,2,1,278,0.0,3,0,0,2732,1,0,126.9,12
2,TEST_0002,COMPONENT2,1982,2010,200,0,0,0,16,5,0.0,0,0,0,11,0,0,44.3,714
3,TEST_0003,COMPONENT3,1404,2009,200,0,0,3,4,163,0.0,4,3,0,8007,0,0,142.8,94
4,TEST_0004,COMPONENT2,8225,2013,200,0,0,0,6,13,0.0,0,0,0,16,0,0,63.4,469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6036,TEST_6036,COMPONENT3,1714,2014,200,0,0,3,130,1047,0.0,65,5,2,1999,0,0,71.2,1163
6037,TEST_6037,COMPONENT3,4131,2016,200,0,0,5,2,736,0.0,5,0,0,693,0,0,137.8,13
6038,TEST_6038,COMPONENT3,4325,2014,200,0,0,0,0,53,0.0,0,0,0,69,0,0,302.2,13
6039,TEST_6039,COMPONENT2,1364,2013,200,0,0,0,62,2,0.0,0,0,0,5,0,0,51.1,478
6040,TEST_6040,COMPONENT1,2397,2016,1597,1,0,0,0,4,0.0,0,2,0,14,0,0,80.0,970

In [10]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Feature Name  52 non-null     object
 1   Description   53 non-null     object
dtypes: object(2)
memory usage: 976.0+ bytes

In [11]:
oil_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14095 entries, 0 to 14094
Data columns (total 54 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   14095 non-null  object
 1   COMPONENT_ARBITRARY  14095 non-null  object
 2   ANONYMOUS_1          14095 non-null  int64
 3   YEAR                 14095 non-null  int64
 4   SAMPLE_TRANSFER_DAY  14095 non-null  int64
 5   ANONYMOUS_2          14095 non-null  int64
 6   AG                   14095 non-null  int64
 7   AL                   14095 non-null  int64
 8   B                    14095 non-null  int64
 9   BA                   14095 non-null  int64
 10  BE                   14095 non-null  int64
 11  CA                   14095 non-null  int64
 12  CD                   12701 non-null  float64
 13  CO                   14095 non-null  int64
 14  CR                   14095 non-null  int64
 15  CU                   14095 non-null  int64
 16  FH2O                 3890 non-null   float64
 17  FNOX                 3890 non-null   float64
 18  FOPTIMETHGLY         3890 non-null   float64
 19  FOXID                3890 non-null   float64
 20  FSO4                 3890 non-null   float64
 21  FTBN                 3890 non-null   float64
 22  FE                   14095 non-null  int64
 23  FUEL                 3890 non-null   float64
 24  H2O                  14095 non-null  float64
 25  K                    11796 non-null  float64
 26  LI                   14095 non-null  int64
 27  MG                   14095 non-null  int64
 28  MN                   14095 non-null  int64
 29  MO                   14095 non-null  int64
 30  NA                   14095 non-null  int64
 31  NI                   14095 non-null  int64
 32  P                    14095 non-null  int64
 33  PB                   14095 non-null  int64
 34  PQINDEX              14095 non-null  int64
 35  S                    14095 non-null  int64
 36  SB                   14095 non-null  int64
 37  SI                   14095 non-null  int64
 38  SN                   14095 non-null  int64
 39  SOOTPERCENTAGE       3890 non-null   float64
 40  TI                   14095 non-null  int64
 41  U100                 2316 non-null   float64
 42  U75                  2316 non-null   float64
 43  U50                  2316 non-null   float64
 44  U25                  2316 non-null   float64
 45  U20                  2316 non-null   float64
 46  U14                  2118 non-null   float64
 47  U6                   2118 non-null   float64
 48  U4                   2118 non-null   float64
 49  V                    14095 non-null  int64
 50  V100                 3724 non-null   float64
 51  V40                  14095 non-null  float64
 52  ZN                   14095 non-null  int64
 53  Y_LABEL              14095 non-null  int64
dtypes: float64(21), int64(31), object(2)
memory usage: 5.8+ MB

In [12]:
oil_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6041 entries, 0 to 6040
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   6041 non-null   object
 1   COMPONENT_ARBITRARY  6041 non-null   object
 2   ANONYMOUS_1          6041 non-null   int64
 3   YEAR                 6041 non-null   int64
 4   ANONYMOUS_2          6041 non-null   int64
 5   AG                   6041 non-null   int64
 6   CO                   6041 non-null   int64
 7   CR                   6041 non-null   int64
 8   CU                   6041 non-null   int64
 9   FE                   6041 non-null   int64
 10  H2O                  6041 non-null   float64
 11  MN                   6041 non-null   int64
 12  MO                   6041 non-null   int64
 13  NI                   6041 non-null   int64
 14  PQINDEX              6041 non-null   int64
 15  TI                   6041 non-null   int64
 16  V                    6041 non-null   int64
 17  V40                  6041 non-null   float64
 18  ZN                   6041 non-null   int64
dtypes: float64(2), int64(15), object(2)
memory usage: 896.8+ KB